// <auto-generated />
namespace achievement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class oauth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oauth));
        
        string IMigrationMetadata.Id
        {
            get { return "201503081250416_oauth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
